version: '3'

services: 
  db:
    image: mariadb
    restart: always
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: qwer1234
      MYSQL_USER: ko
      MYSQL_PASSWORD: qwer1234
      MYSQL_DATABASE: komong
    ports:
      - 3306:3306

  # redis:
  #   image: redis
  #   restart: always
  #   ports:
  #     - "6379:6379"

volumes:
  dbdata:
